# Generated by Django 4.2.11 on 2024-03-26 09:16

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('description', models.TextField(max_length=512, verbose_name='Description')),
                ('square_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Square Meters')),
                ('max_persons', models.PositiveIntegerField(default=5, verbose_name='Maximum Number of Persons')),
                ('bookable_times', models.CharField(blank=True, max_length=128, verbose_name='General Bookable Times')),
                ('pricing', models.TextField(blank=True, max_length=512, verbose_name='Description')),
                ('included_equipment', models.TextField(blank=True, max_length=512, verbose_name='Included Equipment')),
                ('bookable_equipment', models.TextField(blank=True, max_length=512, verbose_name='Bookable Equipment')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
    ]
